/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILZeroRouter, ILZeroRouterInterface } from "../ILZeroRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "burnGood",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "createGood",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "createGoods",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "goodOwner",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "goodId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "goodServiceId",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "goodServiceVoucherIds",
            type: "uint256[]",
          },
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "address[]",
            name: "tokenAddresses",
            type: "address[]",
          },
          {
            internalType: "uint256[]",
            name: "tokenAmounts",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "payers",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "guests",
            type: "address[]",
          },
        ],
        internalType: "struct CreateReservationInput",
        name: "createReservationInput",
        type: "tuple",
      },
    ],
    name: "createReservation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILZeroRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ILZeroRouterInterface {
    return new utils.Interface(_abi) as ILZeroRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILZeroRouter {
    return new Contract(address, _abi, signerOrProvider) as ILZeroRouter;
  }
}
