/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IReservationKernel,
  IReservationKernelInterface,
} from "../IReservationKernel";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "reservationId",
            type: "uint256",
          },
        ],
        internalType: "struct AcceptReservationInput",
        name: "acceptReservationInput",
        type: "tuple",
      },
    ],
    name: "acceptReservation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "reservationId",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokenAddresses",
            type: "address[]",
          },
          {
            internalType: "uint256[]",
            name: "tokenAmounts",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "guests",
            type: "address[]",
          },
        ],
        internalType: "struct AcceptReservationInviteInput",
        name: "acceptReservationInviteInput",
        type: "tuple",
      },
    ],
    name: "acceptReservationInvite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "reservationId",
            type: "uint256",
          },
        ],
        internalType: "struct CancelReservationInput",
        name: "cancelReservationInput",
        type: "tuple",
      },
    ],
    name: "cancelReservation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "goodOwner",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "goodId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "goodServiceId",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "goodServiceVoucherIds",
            type: "uint256[]",
          },
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "address[]",
            name: "tokenAddresses",
            type: "address[]",
          },
          {
            internalType: "uint256[]",
            name: "tokenAmounts",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "payers",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "guests",
            type: "address[]",
          },
        ],
        internalType: "struct CreateReservationInput",
        name: "createReservationInput",
        type: "tuple",
      },
    ],
    name: "createReservation",
    outputs: [
      {
        internalType: "uint256",
        name: "mintedReservationId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintedReservationAmount",
        type: "uint256",
      },
      {
        internalType: "enum ReservationState",
        name: "mintedReservationState",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "reservationId",
            type: "uint256",
          },
        ],
        internalType: "struct DenyReservationInput",
        name: "denyReservationInput",
        type: "tuple",
      },
    ],
    name: "denyReservation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "reservationId",
            type: "uint256",
          },
        ],
        internalType: "struct DenyReservationInviteInput",
        name: "denyReservationInviteInput",
        type: "tuple",
      },
    ],
    name: "denyReservationInvite",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReservationKernel__factory {
  static readonly abi = _abi;
  static createInterface(): IReservationKernelInterface {
    return new utils.Interface(_abi) as IReservationKernelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReservationKernel {
    return new Contract(address, _abi, signerOrProvider) as IReservationKernel;
  }
}
