/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITokenFactory, ITokenFactoryInterface } from "../ITokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenFactoryInterface {
    return new utils.Interface(_abi) as ITokenFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenFactory {
    return new Contract(address, _abi, signerOrProvider) as ITokenFactory;
  }
}
