/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PaymentPoolRegistry,
  PaymentPoolRegistryInterface,
} from "../PaymentPoolRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "paymentPoolDeployer",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "paymentPool",
        type: "address",
      },
    ],
    name: "registerPaymentPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161034c38038061034c83398101604081905261002f91610054565b600180546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102b9806100936000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ccca6b7714610030575b600080fd5b61004361003e366004610231565b610045565b005b6001546001600160a01b031633146100f05760405162461bcd60e51b815260206004820152604160248201527f5061796d656e74506f6f6c52656769737472793a2043616c6c2066726f6d206f60448201527f757473696465206f6620746865205061796d656e74506f6f6c4465706c6f796560648201527f7200000000000000000000000000000000000000000000000000000000000000608482015260a4015b60405180910390fd5b610102816001600160a01b0316610151565b61014e5760405162461bcd60e51b815260206004820152601560248201527f5061796d656e74506f6f6c52656769737472793a20000000000000000000000060448201526064016100e7565b50565b60006001600160a01b0382161580159061017457506001600160a01b0382163b15155b801561022b57506040517f01ffc9a70000000000000000000000000000000000000000000000000000000081527fd4b4f5c50000000000000000000000000000000000000000000000000000000060048201526001600160a01b038316906301ffc9a79060240160206040518083038186803b1580156101f357600080fd5b505afa158015610207573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061022b9190610261565b92915050565b60006020828403121561024357600080fd5b81356001600160a01b038116811461025a57600080fd5b9392505050565b60006020828403121561027357600080fd5b8151801515811461025a57600080fdfea2646970667358221220d32dcaf49abbaaeabe0523000f788c6a05c6c1fe7c6770e95a7d8d622e6cb98164736f6c63430008050033";

type PaymentPoolRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PaymentPoolRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PaymentPoolRegistry__factory extends ContractFactory {
  constructor(...args: PaymentPoolRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "PaymentPoolRegistry";
  }

  deploy(
    paymentPoolDeployer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PaymentPoolRegistry> {
    return super.deploy(
      paymentPoolDeployer,
      overrides || {}
    ) as Promise<PaymentPoolRegistry>;
  }
  getDeployTransaction(
    paymentPoolDeployer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(paymentPoolDeployer, overrides || {});
  }
  attach(address: string): PaymentPoolRegistry {
    return super.attach(address) as PaymentPoolRegistry;
  }
  connect(signer: Signer): PaymentPoolRegistry__factory {
    return super.connect(signer) as PaymentPoolRegistry__factory;
  }
  static readonly contractName: "PaymentPoolRegistry";
  public readonly contractName: "PaymentPoolRegistry";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PaymentPoolRegistryInterface {
    return new utils.Interface(_abi) as PaymentPoolRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PaymentPoolRegistry {
    return new Contract(address, _abi, signerOrProvider) as PaymentPoolRegistry;
  }
}
