/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Routable, RoutableInterface } from "../Routable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "router",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161012138038061012183398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b608f806100926000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063f887ea4014602d575b600080fd5b6000546040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f3fea264697066735822122022adebd0410d368bcfc5526016be43ee16055b25246b2ce5c204111ea9b676e064736f6c63430008050033";

type RoutableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RoutableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Routable__factory extends ContractFactory {
  constructor(...args: RoutableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "Routable";
  }

  deploy(
    router: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Routable> {
    return super.deploy(router, overrides || {}) as Promise<Routable>;
  }
  getDeployTransaction(
    router: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(router, overrides || {});
  }
  attach(address: string): Routable {
    return super.attach(address) as Routable;
  }
  connect(signer: Signer): Routable__factory {
    return super.connect(signer) as Routable__factory;
  }
  static readonly contractName: "Routable";
  public readonly contractName: "Routable";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RoutableInterface {
    return new utils.Interface(_abi) as RoutableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Routable {
    return new Contract(address, _abi, signerOrProvider) as Routable;
  }
}
